<a href="https://colab.research.google.com/github/delcorej/hello-world/blob/main/EDA_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## This is additional practice performing exploratory data analysis##

In [ ]:
#time to download the necessary libraries for this project

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#now time to import the file that I will be utilizing for this project

from google.colab import files
uploaded = files.upload()

Saving ssi-sir-2017-ca-cdph-adult_28procs_.csv.zip to ssi-sir-2017-ca-cdph-adult_28procs_.csv (1).zip

In [ ]:
# now it is time to open this dataframe and see what it is composed of 

df = pd.read_csv('ssi-sir-2017-ca-cdph-adult_28procs_.csv.zip')
df.head()

     Year       State  ... On Track Toward 2020 Goal (0.88, 2017) Notes
0  2017.0  California  ...                                    Yes   NaN
1  2017.0  California  ...                                     No   NaN
2  2017.0  California  ...                                     No   NaN
3  2017.0  California  ...                                     No   NaN
4  2017.0  California  ...                                     No   NaN

[5 rows x 19 columns]

In [ ]:
df. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6841 entries, 0 to 6840
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Year                                    6837 non-null   float64
 1   State                                   6837 non-null   object
 2   HAI                                     6837 non-null   object
 3   Operative_Procedure                     6492 non-null   object
 4   Facility_ID                             6809 non-null   float64
 5   Facility_Name                           6809 non-null   object
 6   Hospital_Category_RiskAdjustment        6809 non-null   object
 7   Hospital_Type                           6810 non-null   object
 8   County                                  6809 non-null   object
 9   Procedure_Count                         6837 non-null   float64
 10  Infection_Count                         6837 non-null   float64
 11  Predicted_Infection_Count               6837 non-null   float64
 12  SIR                                     3586 non-null   float64
 13  SIR_CI_95_Lower_Limit                   3586 non-null   float64
 14  SIR_CI_95_Upper_Limit                   3586 non-null   float64
 15  Comparison                              3586 non-null   object
 16  SIR_2015                                3278 non-null   float64
 17  On Track Toward 2020 Goal (0.88, 2017)  3586 non-null   object
 18  Notes                                   2260 non-null   object
dtypes: float64(9), object(10)
memory usage: 1015.6+ KB

In [ ]:
df.nunique()

Year                                         1
State                                        1
HAI                                          1
Operative_Procedure                         56
Facility_ID                                345
Facility_Name                              345
Hospital_Category_RiskAdjustment             2
Hospital_Type                                7
County                                      51
Procedure_Count                            912
Infection_Count                             67
Predicted_Infection_Count                 2098
SIR                                        466
SIR_CI_95_Lower_Limit                      182
SIR_CI_95_Upper_Limit                     1251
Comparison                                   3
SIR_2015                                   472
On Track Toward 2020 Goal (0.88, 2017)       2
Notes                                        2
dtype: int64

## Summary of Dataset ##
This dataset can be retrieved off of kaggle via [this link](https://www.kaggle.com/aimlanalytics/surgicalsiteinfectionsssishealthcare?select=ssi-sir-2017-ca-cdph-adult_28procs_.csv)

This dataframe was posted by the Center for Disease Control and Prevention National Healthcare Safety Network indicating the amount of surgical site infections in the year of 2017. This dataframe is composed of 19 columns that vary between objects and floats. This means that the data visualization process has to take into account categorical and numerical data. Columns 12 through 18 are missing thousands of values. This means that it would be rather unwise to create or try to utilize these columns when doing any predicitons. The last column is just Notes and contains a lot of missing values- since notes don't have much of an impact in the analysis process it would be wise to drop this row from the dataset. It would be best to list out missing values and see if anything can be done to replace them.

## Checking and Editing Missing Values ##

In [ ]:
#first I am going to drop the notes column as the the amount of missing values is substancial and does not really impact the analysis 
df = df.drop('Notes', 1)
df.head(5)

     Year       State  ... SIR_2015 On Track Toward 2020 Goal (0.88, 2017)
0  2017.0  California  ...     1.07                                    Yes
1  2017.0  California  ...     0.98                                     No
2  2017.0  California  ...     0.97                                     No
3  2017.0  California  ...     1.35                                     No
4  2017.0  California  ...     0.88                                     No

[5 rows x 18 columns]

In [ ]:
#another column I am going to delete is the year column as we already know that all of this data was retrieved in 2017
df = df.drop('Year', 1)
df.head(5)

        State  ... On Track Toward 2020 Goal (0.88, 2017)
0  California  ...                                    Yes
1  California  ...                                     No
2  California  ...                                     No
3  California  ...                                     No
4  California  ...                                     No

[5 rows x 17 columns]

In [ ]:
#Also dropping HAI and State as all of the data is retrieved from California and HAI is just listing that the infection came from a surgical healthcare setting
df = df.drop('HAI', 1)
df = df.drop('State', 1)
df.head(5)

                                 Operative_Procedure  ...  On Track Toward 2020 Goal (0.88, 2017)
0  STATE OF CALIFORNIA POOLED DATA-Abdominal aort...  ...                                     Yes
1   STATE OF CALIFORNIA POOLED DATA-Appendix surgery  ...                                      No
2  STATE OF CALIFORNIA POOLED DATA-Bile duct, liv...  ...                                      No
3    STATE OF CALIFORNIA POOLED DATA-Cardiac surgery  ...                                      No
4   STATE OF CALIFORNIA POOLED DATA-Cesarean section  ...                                      No

[5 rows x 15 columns]